---
title: "Untitled"
---

```{r}
source("http://math.hws.edu/pcqm/pcqm.txt")
source("http://math.hws.edu/pcqm/survey.txt")
```



```{r}
d <- read_csv("http://math.hws.edu/pcqm/Baltzer2007.csv", col_names = TRUE)
d <- d |>
  rename(FullSpecies = Species) |>
  rename(Distance = `Distance m`) |>
  rename(DBH = `DBH cm`) |>
  filter(!is.na(DBH)) |>
  mutate(BasalArea = pi * (DBH/2)^2) |>
  mutate(logDBH = log(DBH)) |>
  mutate(logBA = log(BasalArea))

d <- separate_wider_delim(
  d, cols = "FullSpecies",
  delim = " ",
  names = c("Species"),
  too_many = "drop",
  cols_remove = FALSE)

d <- d |>
  select(c("Point", "Quarter", "Species", "Distance", "DBH"))

importance.val(d)




PauoaFlats <- read_csv("http://math.hws.edu/pcqm/PauoaFlats.csv", col_names = TRUE)
importance.val(PauoaFlats)
Pauola Flats dataset:  http://math.hws.edu/pcqm/PauoaFlats.csv


table(Yuhas$`Genus`)
ggplot(data = Yuhas, aes(x = Genus, y = logDBH)) +
  geom_boxplot() +
  geom_jitter() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

ggplot(data = Yuhas, aes(x = logDBH)) +
  geom_histogram(bins = 10)
ggplot(data = Yuhas, aes(x = logBA)) +
  geom_histogram(bins = 10)

importance.val(Yuhas)
```

https://kjmitchell.shinyapps.io/PCQM_Calculator_for_Importance_Values/

https://kjmitchell.shinyapps.io/PCQM_Calculator_for_Density_Estimates/

https://kjmitchell.shinyapps.io/PCQM_Calculator_for_Angle-Order_Density_Estimates/
  




